Add devise
Thinus01/DailyBlogger pull request #9
Opened 2023-06-19 13:08 UTC by Thinus01

### General requirements

- Made sure that there are no linter errors.
- Made sure that I used correct flow Gitflow.
- Made sure that I documented my work in a professional way.

## Project requirements

- Eliminate the current_user method from the ApplicationController since it will be supplied by devise.
- Install and configure devise.
- Enable users to register.
- Allow users to log in using their email and password. The hashed password should be saved in the database.
- Request email confirmation.
- Enable password resetting.
- Adjust the devise views for registration and login to match the Sneak Peek's wireframes and your design style.

2023-06-20 13:29 UTC, danmainah requested changes
Hi @Thinus01 and @Mutai-Gilbert  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have linter checks running, kindly ensure you have setup your linters config correctly and all linter checks are running and passing 
![image](https://github.com/Thinus01/DailyBlogger/assets/61408860/c43ae905-e0b9-4f9f-8c33-2964d8a94753)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-20 13:51 UTC, julie-ify requested changes
## Hi @Thinus01 and @Mutai-Gilbert,

Good job so far!

## Highlights!
- Good code organization and working devise features ✔️
- Descriptive README ✔️ 

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@julie-ify` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 13:51 UTC, julie-ify commented on app/views/devise/registrations/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] Based on the wireframe layout, the form inputs should be centered on the page, but your form inputs are placed on the left. Kindly fix that.

  ![image](https://github.com/Thinus01/DailyBlogger/assets/81468675/7283cb0d-903e-479b-ae6f-b6b5c5133edd)

2023-06-20 13:51 UTC, julie-ify commented on app/views/devise/sessions/new.html.erb
> +<%= render "devise/shared/links" %>
- [ ] Your login page inputs should be centered on the page, according to the wireframe. Kindly fix that.

  ![fkflfo](https://github.com/Thinus01/DailyBlogger/assets/81468675/8b1cb5d0-2115-460b-abf5-b68d2c90d8a5)

2023-06-22 10:24 UTC, ishimwezachee approved these changes
Hi @Thinus01 and @Mutai-Gilbert,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![image](https://media2.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif)
## Highlights
- Good code organization and working devise features ✔️
- Descriptive README ✔️
- Implemented the requested changes from previous reviewer ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-22 10:24 UTC, ishimwezachee commented on app/views/devise/registrations/new.html.erb
> +
- [ OPTIONAL] You did great to center the both sign in and sign up inputs field and the previous reviewer suggested, but if you look very well on the wireframe., you can see that even the labels such as email, pasword, etc. Are placeholders, they are inside the input field. You can apply that, and center the rest of the text for better look as well.

2023-06-22 10:59 UTC, merged